# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be713b1530337ca0479568eb5dee767175f9f43db6b75ba2e826790d2fc3e567e15be88f26ced3b4b0d94058486b5dc65370c79fed4ecfe1f5ee92be2031e110

test:
  secret_key_base: 285da8fd5b6d92bb63cf1257e888ff51b6557685be60bf386c4839a47520fba0cbf57e8f26c5d93bcb1de13f61330ce990ad9f3edff88619fc7a182a71dce427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
